### ISSUE TITLE
workaround no longer needed: All major browsers automatically fix the issue by adding rel=noopener automatically  if the target attribute is set to _blank   

### ISSUE THREAD

**Issue by stefanibus** [namics/prevent-window-opener-attacks#10]
'[Marcos Imbuerger](https://www.marcosimbuerger.ch/tech-blog/sicherheitsrisiko-target-blank.html)' described the underlying issue very well back in 2019. Since the beginning of 2021 this bug seems to bo fixed for modern browsers as pointed out on  [Stackoverflow](https://stackoverflow.com/a/50709724) with reference to [chromestatus.com](https://chromestatus.com/feature/6140064063029248).   The target=_blank Anchor does imply rel=noopener in all modern browsers by default.  Quote: "All current versions of major browsers"  now automatically fix this issue  **by automatically adding  the behavior of rel="noopener" for any target="_blank" link**. The new browser behaviour will be nullifying this issue.

**Comment by ernscht** [comment]
Think, it makes sense to archive the project.
Does anyone mind?

**Comment by ernscht** [comment]
Package deprecated and will archive repo
