### ISSUE TITLE
Safari Issue

### ISSUE THREAD

**Issue by sean-roberts** [namics/prevent-window-opener-attacks#2]
Hello! Nice work on your library here. I wanted to let you know that I used your github page as a way to test an internal tool I am developing as well for window.opener. I found a bug around safari that I wanted to let you know about. It turns out that setting `window.opener = null` (which is also the same in my current implementation) does not actually work if the new window is a different origin. In fact when you do call `window.opener = null` in this scenario you get an error in the console `TypeError: null is not an object` Which I think is actually a red-herring error. I think it's actually hiding a cross origin security error.

So with that, we both have a bug, and I am not sure what the solution looks like yet. Will let you know if I get a good answer

**Comment by sean-roberts** [comment]
Why I think the bug is actually a CORS security bug being hidden is because if you are in the debugger and just before you set `result.opener = null;` if you run that in the console you get this error:

```
SecurityError (DOM Exception 18): Blocked a frame with origin "http://localhost:8080" from accessing a frame with origin "https://reeko.github.io".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.
```
Though, even if the protocols matched it would argue the origin is not the same

**Comment by sean-roberts** [comment]
Some further debugging looks like that error might be coming from "evil page" instead of using `window.opener = null`.  Specifically I think this line `window.opener.location.href = "evil-fake-page.html"` assumes that opener and location are not null before assigning href. Debugging safari is a nightmare.

With that, there is still a bug but now it seems that safari flat out does not remove the opener when it's set to null.

**Comment by sean-roberts** [comment]
Turns out, using an iframe to redirect folks is the most successful way of doing this:

```
// Given a set of window.open options, open an empty iframe, remove 
// references to the parent frame, call window.open, and finally destroy the iframe
const iframeRedirector = (url, strWindowName, strWindowFeatures)=>{

    // create hidden iframe
    const iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    document.body.appendChild(iframe);

    // inject safe open script
    const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
    const script = iframeDoc.createElement('script');
    script.type = 'text/javascript';
    script.text = `
      window.parent = null;
      window.top = null;
      window.frameElement = null;
      var child = window.open("${url}", "${strWindowName || ''}", "${strWindowFeatures || ''}");
      if (child) { child.opener = null }
    `;
    iframeDoc.body.appendChild(script);

    // remove the injected iframe
    document.body.removeChild(iframe);
}
```

Hope that helps! Have a good one 👋

**Comment by stefanibus** [comment]
For Safari Browsers this bug was closed on October 2018. [Release Notes for Safari Technology Preview 68](https://webkit.org/blog/8475/release-notes-for-safari-technology-preview-68/#:~:text=Changed%20target%3D%22_blank%22%20on%20anchors%20to%20imply%20rel%3D%22noopener%22%20(r237144)):   The article further references to  [Changeset 237144 in webkit](https://trac.webkit.org/changeset/237144/webkit/).

**Comment by ernscht** [comment]
this can be closed then, thanks
